### PR TITLE
Feat/userguide

### PR DESCRIPTION
**Pull request by CasuaIAz**
Updated Userguide.

Will add more, when the app gets more features.

P.s. Sorry for bad England.

### CODE REVIEW

**Review by Kodnot — CHANGES_REQUESTED** [review]
Add instructions on how to use existing keyboard shortcuts & keywords, as per Trello item description.

**Comment by Kodnot** [comment]
[Improve readme with user guide](https://trello.com/c/HFXqeDYe/42-improve-readme-with-user-guide)

**Comment by CasuaIAz** [comment]
Updated it with most recent features I heard from Rokas.

**Review by Kodnot — APPROVED** [review]
Good enough

**Pull request merged**
