### PR TITLE
Added base stuff for testing the project

### PR DESCRIPTION
**Pull request by Kodnot**

### CODE REVIEW

**Review by t-eliks — APPROVED** [review]

**Comment by Kodnot** [comment]
[Create an integration pipeline for the project](https://trello.com/c/NPYuaL6k/70-create-an-integration-pipeline-for-the-project)

**Comment by Kodnot** [comment]
[Investigate options for unit testing WPF](https://trello.com/c/tA53Fiyp/59-investigate-options-for-unit-testing-wpf)

**Pull request merged**
